openapi: 3.1.0
info:
  title: TagMind Orchestrator API
  version: 0.1.0
  description: Orchestrates chat-driven workflows by calling retriever and LLM services.

servers:
  - url: http://localhost:8082
    description: local (docker compose)

tags:
  - name: health
  - name: orchestrator
  - name: conversations

paths:
  /healthz:
    get:
      tags: [health]
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: ok

  /v1/orchestrate:
    post:
      tags: [orchestrator]
      summary: Orchestrate a single user message into an answer
      parameters:
        - $ref: "#/components/parameters/XRequestId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrchestrateRequest"
      responses:
        "200":
          description: Orchestration result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrchestrateResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/conversations/upsert:
    post:
      tags: [conversations]
      summary: Create or update a conversation session for a contact
      parameters:
        - $ref: "#/components/parameters/XRequestId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConversationsUpsertRequest"
      responses:
        "200":
          description: Upserted session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationsUpsertResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/conversations/message:
    post:
      tags: [conversations]
      summary: Store an incoming message and optionally generate a suggested reply
      parameters:
        - $ref: "#/components/parameters/XRequestId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConversationsMessageRequest"
      responses:
        "200":
          description: Decision and (optional) suggestion
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationsMessageResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/conversations/tag:
    post:
      tags: [conversations]
      summary: Handle @tagmind commands with tag-specific routing
      parameters:
        - $ref: "#/components/parameters/XRequestId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TagRequest"
      responses:
        "200":
          description: Tag routing response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  parameters:
    XRequestId:
      name: X-Request-Id
      in: header
      required: false
      description: Optional request correlation id. If missing, server generates one.
      schema:
        type: string
        minLength: 8
        maxLength: 128

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            badRequest:
              value:
                requestId: "req_123"
                code: "BAD_REQUEST"
                message: "Invalid payload"
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            internal:
              value:
                requestId: "req_123"
                code: "INTERNAL"
                message: "Unexpected error"

  schemas:
    OrchestrateRequest:
      type: object
      required: [userId, chatId, message]
      properties:
        userId:
          type: string
          description: Stable user id (Telegram user id or internal).
          example: "tg:123456"
        chatId:
          type: string
          description: Stable chat id (Telegram chat id or internal).
          example: "tg_chat:987654"
        message:
          type: string
          minLength: 1
          maxLength: 4000
          example: "When did World War 2 start?"
        mode:
          type: string
          description: Orchestration mode
          enum: [chat, no_context, llm_only]
          default: chat
        locale:
          type: string
          description: Requested locale for the final answer (BCP-47)
          example: "ru-RU"
        context:
          type: object
          additionalProperties: true
          description: Optional context hints (client-provided)

    OrchestrateResponse:
      type: object
      required: [requestId, answer]
      properties:
        requestId:
          type: string
          example: "req_123"
        answer:
          type: string
          example: "World War II began on September 1, 1939, when Germany invaded Poland."
        used:
          type: object
          description: Debug metadata (safe to expose)
          additionalProperties: true

    ErrorResponse:
      type: object
      required: [requestId, code, message]
      properties:
        requestId:
          type: string
        code:
          type: string
          example: "BAD_REQUEST"
        message:
          type: string
          example: "Invalid payload"

    ConversationMode:
      type: string
      enum: [OFF, SUGGEST]

    ConversationsUpsertRequest:
      type: object
      required: [contactId, mode]
      properties:
        contactId:
          type: string
          description: Stable contact id (e.g., Telegram user id)
          example: "tg:12345"
        mode:
          $ref: "#/components/schemas/ConversationMode"

    ConversationsUpsertResponse:
      type: object
      required: [requestId, sessionId, contactId, mode]
      properties:
        requestId:
          type: string
          example: "req_123"
        sessionId:
          type: string
          format: uuid
        contactId:
          type: string
        mode:
          $ref: "#/components/schemas/ConversationMode"

    ConversationsDecision:
      type: string
      enum: [DO_NOT_RESPOND, SUGGEST]

    ConversationsMessageRequest:
      type: object
      required: [contactId, message]
      properties:
        contactId:
          type: string
          example: "tg:12345"
        message:
          type: string
          minLength: 1
          maxLength: 4000

    ConversationsMessageResponse:
      type: object
      required: [requestId, decision, sessionId]
      properties:
        requestId:
          type: string
        decision:
          $ref: "#/components/schemas/ConversationsDecision"
        suggestedReply:
          type: string
          nullable: true
        sessionId:
          type: string
          format: uuid
        used:
          type: object
          additionalProperties: true

    TagName:
      type: string
      description: Supported @tagmind command tags.
      enum: [help, llm, web, recap, judge, fix, plan, safe]

    TagDecision:
      type: string
      enum: [RESPOND, DO_NOT_RESPOND]

    TagRequest:
      type: object
      required: [contactId, tag]
      properties:
        contactId:
          type: string
          example: "tg:12345"
        tag:
          $ref: "#/components/schemas/TagName"
        count:
          type: integer
          minimum: 1
          description: Optional number of history messages to fetch (recap/judge/fix).
        payload:
          type: string
          description: Optional free-form payload provided after the tag.
          example: "Summarize action items"
        locale:
          type: string
          example: "ru-RU"
        text:
          type: string
          description: Original message text as received from the client (before parsing).

    TagResponse:
      type: object
      required: [requestId, decision, sessionId, contactId, tag]
      properties:
        requestId:
          type: string
        decision:
          $ref: "#/components/schemas/TagDecision"
        replyText:
          type: string
          nullable: true
          description: Text to send back to the channel when decision is RESPOND.
        sessionId:
          type: string
          format: uuid
        contactId:
          type: string
        tag:
          $ref: "#/components/schemas/TagName"
        used:
          type: object
          additionalProperties: true
